buildscript {
    repositories {
        maven {
            name = "Minecraft Forge"
            url = "https://maven.minecraftforge.net/"
        }
    }
    dependencies {
        classpath "net.minecraftforge.gradle:ForgeGradle:4.+"
    }
}
apply plugin: "net.minecraftforge.gradle"
apply plugin: "maven-publish"

version = "1.1.0." + ('git rev-list --count HEAD'.execute().text.trim()) + "-1.12.2"
group = "net.buildtheearth"
archivesBaseName = "terraplusplus"

compileJava {
    sourceCompatibility = targetCompatibility = "1.8"
}

minecraft {
    mappings channel: "stable", version: "39-1.12"

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'debug'
            property 'fml.coreMods.load', 'io.github.opencubicchunks.cubicchunks.core.asm.coremod.CubicChunksCoreMod,io.github.opencubicchunks.cubicchunks.cubicgen.asm.coremod.CubicGenCoreMod'
            property 'mixin.env.disableRefMap', 'true'
        }

        server {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'debug'
            property 'fml.coreMods.load', 'io.github.opencubicchunks.cubicchunks.core.asm.coremod.CubicChunksCoreMod,io.github.opencubicchunks.cubicchunks.cubicgen.asm.coremod.CubicGenCoreMod'
            property 'mixin.env.disableRefMap', 'true'
        }
    }
}

repositories {
    maven {
        name = "DaPorkchop_"
        url = "https://maven.daporkchop.net/"
    }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.12.2-14.23.5.2864'

    // We have to use this as deobfProvided even though there's a :dev version of the artifact because otherwise mixin
    // prevents the mod from loading when running in a dev environment.
    implementation fg.deobf("io.github.opencubicchunks:cubicchunks:1.12.2-0.0.1282.0-SNAPSHOT") {
        transitive = false
    }

    implementation("io.github.opencubicchunks:cubicworldgen:1.12.2-0.0.206.0-SNAPSHOT:dev") {
        transitive = false
    }

    implementation "org.apache.commons:commons-imaging:1.0.0-alpha5"

    implementation "com.fasterxml.jackson.core:jackson-databind:2.11.2"

    implementation("net.daporkchop.lib:binary:0.5.7-SNAPSHOT")  {
        exclude group: "io.netty"
    }

    testCompile "junit:junit:4.12"

    implementation "org.projectlombok:lombok:1.18.16"
    annotationProcessor "org.projectlombok:lombok:1.18.16"
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = "net.buildtheearth"
            artifactId = "terraplusplus"
            version = project.version

            from components.java

            artifacts.clear()
        }
    }
}
