buildscript {
    repositories {
        maven {
            name = "Minecraft Forge"
            url = "https://maven.minecraftforge.net/"
        }
    }
    dependencies {
        classpath "net.minecraftforge.gradle:ForgeGradle:6.+"
    }
}
apply plugin: "net.minecraftforge.gradle"
apply plugin: "maven-publish"

version = "${mod_version_base}." + ('git rev-list --count HEAD'.execute().text.trim()) + "-${minecraft_version}"
group = "net.buildtheearth"
archivesBaseName = "terraplusplus"

compileJava {
    sourceCompatibility = targetCompatibility = "1.8"
}

minecraft {
    mappings channel: mapping_channel, version: mapping_version

    runs {
        configureEach {
            workingDirectory project.file('run')

            // Log4J log level for stdout
            property 'forge.logging.console.level', 'debug'

            // FML debugging info dumps (comma-separated list)
            // - "SCAN": For mods scan.
            // - "REGISTRIES": For firing of registry events.
            // - "REGISTRYDUMP": For getting the contents of all registries.
            property 'forge.logging.markers', 'SCAN'

            // Handle coremods:
            // - instruct FML to load the CC and CWG coremods as it doesn't know how to find them in the ForgeGradle 3+ dev environment
            // - instruct Mixin to not use obfuscated names in the deobfuscated dev environment
            property 'fml.coreMods.load', 'io.github.opencubicchunks.cubicchunks.core.asm.coremod.CubicChunksCoreMod,io.github.opencubicchunks.cubicchunks.cubicgen.asm.coremod.CubicGenCoreMod'
            property 'mixin.env.disableRefMap', 'true'
        }

        client { }

        server {
            args 'nogui'
        }
    }
}

repositories {
    maven {
        name = "DaPorkchop_"
        url = "https://maven.daporkchop.net/"
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    implementation "org.projectlombok:lombok:${lombok_version}"
    annotationProcessor "org.projectlombok:lombok:${lombok_version}"

    // We have to explicitly deobfuscate this instead of using the :dev version of the artifact because otherwise mixin
    // prevents the mod from loading when running in a dev environment.
    implementation fg.deobf("io.github.opencubicchunks:cubicchunks:${cubicchunks_version}") {
        transitive = false
    }
    implementation("io.github.opencubicchunks:cubicworldgen:${cubicworldgen_version}:dev") {
        transitive = false
    }

    implementation "org.apache.commons:commons-imaging:${apache_commons_imaging_version}"
    implementation "com.fasterxml.jackson.core:jackson-databind:${jackson_version}"
    implementation("net.daporkchop.lib:binary:${porklib_version}")  {
        exclude group: "io.netty"
    }

    testImplementation(platform("org.junit:junit-bom:${junit_version}"))
    testImplementation('org.junit.jupiter:junit-jupiter')
    testRuntimeOnly('org.junit.platform:junit-platform-launcher')
}


test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = "net.buildtheearth"
            artifactId = "terraplusplus"
            version = project.version

            from components.java

            artifacts.clear()
        }
    }
}
