# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G

# workaround: https://www.abrarsyed.com/ForgeGradleVersion.json doesn't have a valid SSL certificate any more
net.minecraftforge.gradle.disableUpdateChecker=true

# Platform versions (Minecraft, Minecraft Forge & obfuscation mappings)
minecraft_version=1.12.2
forge_version=14.23.5.2864
mapping_channel=stable
mapping_version=39-1.12

# Build time dependencies
lombok_version=1.18.16

# Mod dependency versions (CubicChunks & CubicWorldGen)
cubicchunks_version=1.12.2-0.0.1282.0-SNAPSHOT
cubicworldgen_version=1.12.2-0.0.206.0-SNAPSHOT

# Library dependencies
apache_commons_imaging_version=1.0.0-alpha5
jackson_version=2.11.2
porklib_version=0.5.7-SNAPSHOT

# Test dependency versions
junit_version=5.14.4

mod_id=terraplusplus
mod_name=TerraPlusPlus
mod_version_base=1.1.0
mod_url=https://buildtheearth.net